### ISSUE TITLE
Меню "Сгенерировать рейсы";

### ISSUE THREAD

**Issue by 3dlfive** [3dlfive/stepbooking#63]

**Comment by 3dlfive** [comment]
Можно сделать  под меню типо еесли файл уже есть ? спросить вы уверены что хотите перегенерировать базу

**Comment by khatsubavladimir** [comment]
тогда надо что-то придумать с букингами рейсы для которых сотрутся при генерации новых, можно удалить их все, но тогда это уже будет не "сгенерировать рейсы", а "начать всё заново"
