### ISSUE TITLE
Найти по getSpecific для создания букинга

### ISSUE THREAD

**Issue by 3dlfive** [3dlfive/stepbooking#65]

**Comment by khatsubavladimir** [comment]
метод поиска рейса по ID создавался для создания букинга, не думаю что есть смысл в меню возможность просто по ID искать рейс, но исходя из задания:
"Користувачеві пропонується послідовно ввести таку інформацію: місце призначення, дата, кількість осіб (скільки потрібно купити квитків). Після цього програма повинна виконати пошук рейсів, які задовольняють заданим умовам (на рейсі вільних місць має бути не менше кількості зазначених пасажирів)."
должен быть поиск рейса по этим трём характеристикам

.getSpecific(...) находит нужные рейсы, нужно сделать ввод и передать ему данные, а потом вывести результат на экран

**Comment by 3dlfive** [comment]
Так что нужно сделать? какой твой вариант, 
в Создании букинга вс' всунуть?

**Comment by 3dlfive** [comment]
мой вариант отдельное меню поиск рейсов,
после поиска по дате и места будет список 
ИД Дата Время Назначение

и у пользователя спрашиваем какой рейс нужен? введите ИД .. 
ФИО и количество

**Comment by 3dlfive** [comment]
Или начать с вопросов getSpecificDate 
потом спросить ИД?
и количество  имя Фамили , пассажиров

**Comment by khatsubavladimir** [comment]
нужно сначала спросить 
дату (когда человек хочет лететь)
аеропорт (куда хочет лететь)
места (которые хочет занять)
это передать в getSpecific, вывесть результаты поиска
потом спрашивается ID какой из рейсов человеку больше всего понравился и для этого рейса создаётся букинг
либо если список результатов пустой или человеку не нравится ни один рейс должна быть опция не создавать букинг
